<?php
/**
 * Bulgarian Cities
 * List generated from https://en.wikipedia.org/wiki/List_of_cities_and_towns_in_Bulgaria
 */
global $cities;

$cities['BG'] = array(
	'BG-01' => array( // Blagoevgrad.
		"Bansko",
		"Belitsa",
		"Blagoevgrad",
		"Gotse Delchev",
		"Dobrinishte",
		"Kresna",
		"Melnik",
		"Petrich",
		"Razlog",
		"Sandanski",
		"Simitli",
		"Hadzhidimovo",
		"Yakoruda",
	),
	'BG-02' => array( // Burgas.
		"Aheloy",
		"Ahtopol",
		"Aytos",
		"Balgarovo",
		"Burgas",
		"Chernomorets",
		"Kableshkovo",
		"Kameno",
		"Karnobat",
		"Kiten",
		"Malko Tarnovo",
		"Nesebar",
		"Obzor",
		"Pomorie",
		"Primorsko",
		"Sozopol",
		"Sredets",
		"Sungurlare",
		"Sveti Vlas",
		"Tsarevo",
	),
	'BG-03' => array( // Varna.
		"Aksakovo",
		"Beloslav",
		"Byala",
		"Dalgopol",
		"Devnya",
		"Dolni Chiflik",
		"Ignatievo",
		"Provadiya",
		"Suvorovo",
		"Valchi Dol",
		"Varna",
	),
	'BG-04' => array( // Veliko Tarnovo.
		"Byala Cherkva",
		"Debelec",
		"Dolna Oryahovitsa",
		"Elena",
		"Gorna Oryahovitsa",
		"Kilifarevo",
		"Lyaskovets",
		"Pavlikeni",
		"Polski Trambesh",
		"Strazhitsa",
		"Suhindol",
		"Svishtov",
		"Veliko Tarnovo",
		"Zlataritsa",
	),
	'BG-05' => array( // Vidin.
		"Belogradchik",
		"Bregovo",
		"Dimovo",
		"Dunavtsi",
		"Gramada",
		"Kula",
		"Vidin",
	),
	'BG-06' => array( // Vratsa.
		"Byala Slatina",
		"Kozloduy",
		"Krivodol",
		"Mezdra",
		"Mizia",
		"Oryahovo",
		"Roman",
		"Vratsa",
	),
	'BG-07' => array( // Gabrovo.
		"Dryanovo",
		"Gabrovo",
		"Plachkovtsi",
		"Sevlievo",
		"Tryavna",
	),
	'BG-08' => array( // Dobrich.
		"Balchik",
		"Dobrich",
		"General Toshevo",
		"Kavarna",
		"Shabla",
		"Tervel",
	),
	'BG-09' => array( // Kardzhali.
		"Ardino",
		"Dzhebel",
		"Kardzhali",
		"Krumovgrad",
		"Momchilgrad",
	),
	'BG-10' => array( // Kyustendil.
		"Boboshevo",
		"Bobov Dol",
		"Dupnitsa",
		"Kocherinovo",
		"Kyustendil",
		"Rila",
		"Sapareva Banya",
	),
	'BG-11' => array( // Lovech.
		"Apriltsi",
		"Letnitsa",
		"Lovech",
		"Lukovit",
		"Teteven",
		"Troyan",
		"Ugarchin",
		"Yablanitsa",
	),
	'BG-12' => array( // Montana.
		"Berkovitsa",
		"Boychinovtsi",
		"Brusartsi",
		"Chiprovtsi",
		"Lom",
		"Montana",
		"Valchedram",
		"Varshets",
	),
	'BG-13' => array( // Pazardzhik.
		"Batak",
		"Belovo",
		"Bratsigovo",
		"Kostandovo",
		"Panagyurishte",
		"Pazardzhik",
		"Peshtera",
		"Rakitovo",
		"Sarnitsa",
		"Septemvri",
		"Strelcha",
		"Velingrad",
		"Vetren",
	),
	'BG-14' => array( // Pernik.
		"Batanovtsi",
		"Breznik",
		"Pernik",
		"Radomir",
		"Tran",
		"Zemen",
	),
	'BG-15' => array( // Pleven.
		"Belene",
		"Cherven Bryag",
		"Dolna Mitropoliya",
		"Dolni Dabnik",
		"Gulyantsi",
		"Iskar",
		"Knezha",
		"Koynare",
		"Levski",
		"Nikopol",
		"Pleven",
		"Pordim",
		"Slavyanovo",
		"Trastenik",
	),
	'BG-16' => array( // Plovdiv.
		"Asenovgrad",
		"Banya",
		"Brezovo",
		"Hisarya",
		"Kalofer",
		"Karlovo",
		"Klisura",
		"Krichim",
		"Kuklen",
		"Laki",
		"Parvomay",
		"Perushtitsa",
		"Plovdiv",
		"Rakovski",
		"Sadovo",
		"Saedinenie",
		"Sopot",
		"Stamboliyski",
	),
	'BG-17' => array( // Razgrad.
		"Isperih",
		"Kubrat",
		"Loznitsa",
		"Razgrad",
		"Tsar Kaloyan",
		"Zavet",
	),
	'BG-18' => array( // Ruse.
		"Borovo",
		"Byala",
		"Dve Mogili",
		"Glodzhevo",
		"Marten",
		"Ruse",
		"Senovo",
		"Slivo Pole",
		"Vetrovo",
	),
	'BG-19' => array( // Silistra.
		"Alfatar",
		"Dulovo",
		"Glavinitsa",
		"Silistra",
		"Tutrakan",
	),
	'BG-20' => array( // Sliven.
		"Kermen",
		"Kotel",
		"Nova Zagora",
		"Shivachevo",
		"Sliven",
		"Tvarditsa",
	),
	'BG-21' => array( // Smolyan.
		"Chepelare",
		"Devin",
		"Dospat",
		"Madan",
		"Nedelino",
		"Rudozem",
		"Smolyan",
		"Zlatograd",
	),
	'BG-22' => array( // Sofia-Grad.
		"Bankya",
		"Buhovo",
		"Novi Iskar",
		"Sofia",
	),
	'BG-23' => array( // Sofia Province.
		"Botevgrad",
		"Bozhurishte",
		"Dolna Banya",
		"Dragoman",
		"Elin Pelin",
		"Etropole",
		"Godech",
		"Ihtiman",
		"Koprivshtitsa",
		"Kostenets",
		"Kostinbrod",
		"Momin Prohod",
		"Pirdop",
		"Pravets",
		"Samokov",
		"Slivnitsa",
		"Svoge",
		"Zlatitsa",
	),
	'BG-24' => array( // Stara Zagora.
		"Chirpan",
		"Galabovo",
		"Gurkovo",
		"Kazanlak",
		"Kran",
		"Maglizh",
		"Nikolaevo",
		"Pavel Banya",
		"Radnevo",
		"Shipka",
		"Stara Zagora",
	),
	'BG-25' => array( // Targovishte.
		"Antonovo",
		"Omurtag",
		"Opaka",
		"Popovo",
		"Targovishte",
	),
	'BG-26' => array( // Haskovo.
		"Dimitrovgrad",
		"Harmanli",
		"Haskovo",
		"Ivaylovgrad",
		"Lyubimets",
		"Madzharovo",
		"Merichleri",
		"Simeonovgrad",
		"Svilengrad",
		"Topolovgrad",
	),
	'BG-27' => array( // Shumen.
		"Kaolinovo",
		"Kaspichan",
		"Novi Pazar",
		"Pliska",
		"Shumen",
		"Smyadovo",
		"Varbitsa",
		"Veliki Preslav",
	),
	'BG-28' => array( // Yambol.
		"Bolyarovo",
		"Elhovo",
		"Straldzha",
		"Yambol",
	),
);
